id: ICE76577C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T10:17:21+00:00'
last_modified: '2022-06-07T12:13:01.209959+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG16610
  title: བྱང་ཆུབ་སེམས་དཔའི་ས་དང་ཚོམས་ཞེས་བྱ་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    FD41:
      image_group_id: I1KG16646
      title: Volume 1 of byang chub sems dpa'i sa dang tshoms zhes bya ba/
      total_pages: 596
      order: 1
      base_file: FD41.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
